### ISSUE TITLE
Node engine is too restrictive

### ISSUE THREAD

**Issue by DuBistKomisch** [Netflix/ember-batch-request#3]
https://github.com/Netflix/ember-batch-request/blob/bc7bff1e622ff56326df56fa57a881abb483de89/package.json#L27

This prevents me from even installing the addon with yarn unless I'm using exactly 6.7.0, but I assume npm only gives a warning.

You should either set it to `>= 4` or not at all, since I assume it doesn't need any particular node features.

**Comment by jamesmenera** [comment]
@DuBistKomisch Yeah this is a fair request

**Comment by DuBistKomisch** [comment]
Thanks, in hindsight I should have made a PR as well... would have taken 5 seconds haha.

**Comment by jamesmenera** [comment]
Alright new release `0.0.21` has this change
